// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Veldrid.PBR.Unlit
{
    /// <summary>
    ///     Class to produce the template output
    /// </summary>
#line 1 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"
    [GeneratedCode("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class UnlitVertexShader : UnlitVertexShaderBase
    {
        /// <summary>
        ///     Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            Write(@"#version 450

layout(set = 0, binding = 0) uniform ViewProjection
{
    mat4 View;
    mat4 Projection;
};
layout(set = 0, binding = 1) uniform ModelBuffer
{
    mat4 WorldTransform;
};
struct MapUV
{
    vec3 X;
    int Set;
    vec3 Y;
};
layout (set=1, binding=0) uniform UnlitMaterialArguments
{
    vec4 BaseColorFactor;
    float AlphaCutoff;
    MapUV BaseColorMapUV; 
};

");

#line 30 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"

            var numColorComponents = 0;
            var hasTexCoord0 = false;
            var hasTexCoord1 = false;
            for (var locationIndex = 0; locationIndex < _key.Elements.Elements.Length; ++locationIndex)
            {
                var element = _key.Elements.Elements[locationIndex];


#line default
#line hidden
                Write("layout(location = ");

#line 38 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"
                Write(ToStringHelper.ToStringWithCulture(locationIndex));

#line default
#line hidden
                Write(") in ");

#line 38 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"
                Write(ToStringHelper.ToStringWithCulture(SpirVTypeFromFormat(element.Format)));

#line default
#line hidden
                Write(" ");

#line 38 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"
                Write(ToStringHelper.ToStringWithCulture(element.Name));

#line default
#line hidden
                Write(";\r\n");

#line 39 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"

                if (element.Name == "COLOR_0")
                    numColorComponents = element.Format.GetNumComponents();
                else if (element.Name == "TEXCOORD_0")
                    hasTexCoord0 = true;
                else if (element.Name == "TEXCOORD_1") hasTexCoord1 = true;
            }


#line default
#line hidden
            Write(@"
layout(location = 0) out vec4 v_Color0;
layout(location = 1) out vec2 v_UVCoord0;
layout(location = 2) out vec2 v_UVCoord1;

void main()
{
    vec4 worldPosition = WorldTransform * vec4(POSITION, 1);
    vec4 viewPosition = View * worldPosition;
    vec4 clipPosition = Projection * viewPosition;
");

#line 55 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"

            if (hasTexCoord0) Write("    v_UVCoord0 = TEXCOORD_0;\r\n");
            else Write("    v_UVCoord0 = vec2(0,0);\r\n");
            if (hasTexCoord1) Write("    v_UVCoord1 = TEXCOORD_1;\r\n");
            else Write("    v_UVCoord1 = vec2(0,0);\r\n");

            switch (numColorComponents)
            {
                case 0:


#line default
#line hidden
                    Write("    v_Color0 = vec4(1,1,1,1);\r\n");

#line 64 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"

                    break;
                case 1:


#line default
#line hidden
                    Write("    v_Color0 = vec4(COLOR_0,0,0,1);\r\n");

#line 69 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"

                    break;
                case 2:


#line default
#line hidden
                    Write("    v_Color0 = vec4(COLOR_0.x,COLOR_0.y,0,1);\r\n");

#line 74 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"

                    break;
                case 3:


#line default
#line hidden
                    Write("    v_Color0 = vec4(COLOR_0.x,COLOR_0.y,COLOR_0.z,1);\r\n");

#line 79 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"

                    break;
                case 4:


#line default
#line hidden
                    Write("    v_Color0 = vec4(COLOR_0.x,COLOR_0.y,COLOR_0.z,COLOR_0.w);\r\n");

#line 84 "C:\github\Veldrid.PBR\src\Veldrid.PBR\Unlit\UnlitVertexShader.tt"

                    break;
            }


#line default
#line hidden
            Write("    gl_Position = clipPosition;\r\n}");
            return GenerationEnvironment.ToString();
        }
    }

#line default
#line hidden

    #region Base class

    /// <summary>
    ///     Base class for this transformation
    /// </summary>
    [GeneratedCode("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class UnlitVertexShaderBase
    {
        #region Fields

        private StringBuilder generationEnvironmentField;
        private CompilerErrorCollection errorsField;
        private List<int> indentLengthsField;
        private bool endsWithNewline;

        #endregion

        #region Properties

        /// <summary>
        ///     The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected StringBuilder GenerationEnvironment
        {
            get
            {
                if (generationEnvironmentField == null) generationEnvironmentField = new StringBuilder();
                return generationEnvironmentField;
            }
            set => generationEnvironmentField = value;
        }

        /// <summary>
        ///     The error collection for the generation process
        /// </summary>
        public CompilerErrorCollection Errors
        {
            get
            {
                if (errorsField == null) errorsField = new CompilerErrorCollection();
                return errorsField;
            }
        }

        /// <summary>
        ///     A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private List<int> indentLengths
        {
            get
            {
                if (indentLengthsField == null) indentLengthsField = new List<int>();
                return indentLengthsField;
            }
        }

        /// <summary>
        ///     Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent { get; private set; } = "";

        /// <summary>
        ///     Current transformation session
        /// </summary>
        public virtual IDictionary<string, object> Session { get; set; }

        #endregion

        #region Transform-time helpers

        /// <summary>
        ///     Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend)) return;
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (GenerationEnvironment.Length == 0
                || endsWithNewline)
            {
                GenerationEnvironment.Append(CurrentIndent);
                endsWithNewline = false;
            }

            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(Environment.NewLine, StringComparison.CurrentCulture)) endsWithNewline = true;
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if (CurrentIndent.Length == 0)
            {
                GenerationEnvironment.Append(textToAppend);
                return;
            }

            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(Environment.NewLine, Environment.NewLine + CurrentIndent);
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (endsWithNewline)
                GenerationEnvironment.Append(textToAppend, 0, textToAppend.Length - CurrentIndent.Length);
            else
                GenerationEnvironment.Append(textToAppend);
        }

        /// <summary>
        ///     Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            Write(textToAppend);
            GenerationEnvironment.AppendLine();
            endsWithNewline = true;
        }

        /// <summary>
        ///     Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            Write(string.Format(CultureInfo.CurrentCulture, format, args));
        }

        /// <summary>
        ///     Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            WriteLine(string.Format(CultureInfo.CurrentCulture, format, args));
        }

        /// <summary>
        ///     Raise an error
        /// </summary>
        public void Error(string message)
        {
            var error = new CompilerError();
            error.ErrorText = message;
            Errors.Add(error);
        }

        /// <summary>
        ///     Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            var error = new CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            Errors.Add(error);
        }

        /// <summary>
        ///     Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if (indent == null) throw new ArgumentNullException("indent");
            CurrentIndent = CurrentIndent + indent;
            indentLengths.Add(indent.Length);
        }

        /// <summary>
        ///     Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            var returnValue = "";
            if (indentLengths.Count > 0)
            {
                var indentLength = indentLengths[indentLengths.Count - 1];
                indentLengths.RemoveAt(indentLengths.Count - 1);
                if (indentLength > 0)
                {
                    returnValue = CurrentIndent.Substring(CurrentIndent.Length - indentLength);
                    CurrentIndent = CurrentIndent.Remove(CurrentIndent.Length - indentLength);
                }
            }

            return returnValue;
        }

        /// <summary>
        ///     Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            indentLengths.Clear();
            CurrentIndent = "";
        }

        #endregion

        #region ToString Helpers

        /// <summary>
        ///     Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private IFormatProvider formatProviderField = CultureInfo.InvariantCulture;

            /// <summary>
            ///     Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public IFormatProvider FormatProvider
            {
                get => formatProviderField;
                set
                {
                    if (value != null) formatProviderField = value;
                }
            }

            /// <summary>
            ///     This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if (objectToConvert == null) throw new ArgumentNullException("objectToConvert");
                var t = objectToConvert.GetType();
                var method = t.GetMethod("ToString", new[]
                {
                    typeof(IFormatProvider)
                });
                if (method == null)
                    return objectToConvert.ToString();
                return (string) method.Invoke(objectToConvert, new object[]
                {
                    formatProviderField
                });
            }
        }

        /// <summary>
        ///     Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper { get; } = new ToStringInstanceHelper();

        #endregion
    }

    #endregion
}